version: '3.7'

services:
    database:
        image: mariadb
        environment:
            - MYSQL_DATABASE=dodona
            - MYSQL_USER=dodona
            - MYSQL_ROOT_PASSWORD=dodona
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "--user=root", "--password=dodona", "--silent"]
            interval: 5s
            timeout: 1m
            retries: 12
        ports:
            - "3306:3306"

    dodona:
        hostname: dodona.localhost
        build: .
        depends_on:
            - database
        ports:
            - "3000:3000"