name: Publish Docker image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Dodona repo
      uses: actions/checkout@v2
      with:
        repository: 'dodona-edu/dodona'
        ref: 'develop'
        path: dodona
    - name: Checkout docker files
      uses: actions/checkout@v2
      with:
        path: docker-files
    - name: Copy files
      run: |
        cp docker-files/* dodona/
        cd dodona
    - run: pwd
    - run: ls
    - name: Login to the container registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Download the latest image for caching
      run: docker pull ghcr.io/dodona-edu/dodona:develop-latest
    - name: Build the new image
      run: docker build . -t ghcr.io/dodona-edu/dodona:develop-latest --cache-from ghcr.io/dodona-edu/dodona:develop-latest
    - name: Push the new image
      run: docker push ghcr.io/dodona-edu/dodona:develop-latest
